config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # minimal carts and cats routes for dev purposes
  resources :cats
  resources :cart_cats, only: %i[create update destroy]
  resources :carts
  get 'download_cart_zip', to: "carts#download_cart_zip"
  resources :charges
  resources :profiles

  get 'admin', to: 'admin#index_admin'

  namespace :admin do
    resources :cats
    resources :carts
    resources :users
  end

  # root 'cats#index'
  root 'welcome#index'

  # static_pages
  get 'team_project', to: 'static_pages#team_project'
end

app/models/cat.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: cats
#
#  id           :bigint(8)        not null, primary key
#  description  :text
#  image        :text
#  is_available :boolean          default(TRUE)
#  price        :decimal(, )      default(0.0)
#  created_at   :datetime         not null
#  title        :string
#  updated_at   :datetime         not null
#  seller_id    :bigint(8)
#
# Indexes
#
#  index_cats_on_seller_id  (seller_id)
#

class Cat < ApplicationRecord
  validates :title, :price, presence: true
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed. " }
  validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed. " }
  validates :price, length: { maximum: 6 }

  has_one_attached :item_picture # active storage
  belongs_to :seller, class_name: 'User', optional: true
  has_many :cart_cats, dependent: :destroy

  before_destroy :ensure_deletable, prepend: true

  def user_seller
    Cat.find(id).seller.profile.full_name_or_email
  end

  def self.from_seller(seller)
    where(seller: seller)
  end

  def ensure_deletable
    # TODO: Not sure this works.. but raises a PG error anyway
    raise "Will not delete because included in carts" unless cart_cats.empty?
  end
end

app/controllers/admin/cats_controller.rb
# frozen_string_literal: true

module Admin
  class CatsController < AdminController
    def index
      @cats = Cat.all.order(:id).reverse
    end

    def new
      @cat = Cat.new
    end

    def create
      @cat = Cat.new(title: params[:title], description: params[:description], price: params[:price])
      @cat.item_picture.attach(params[:item_picture])

      if @cat.save
        redirect_to admin_cats_path, flash: { success: "New image created" }
      else
        render 'new', flash: { error: "Check if all fields a completed" }
      end
    end

    def show
      @cat = Cat.find(params[:id])
    end

    def edit
      @cat = Cat.find(params[:id])
    end

    def update
      cat_params = params.permit(:title, :description, :price, :is_available)

      if !params[:item_picture].nil?
        @cat.item_picture.attach(params[:item_picture])
      end

      if @cat.update(cat_params)
        redirect_to admin_cats_path, flash: { success: "Item updated" }
      else
        render 'index'
      end
    end

    def destroy
      @cat = Cat.find(params[:id])
      @cat.destroy
      redirect_to admin_cats_path
    end
  end
end

app/controllers/cats_controller.rb
# frozen_string_literal: true

class CatsController < ApplicationController
  def index
    @cats = Cat.where('is_available').order("created_at desc")
    @cart_cats = current_cart.cart_cats if user_signed_in?
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    if user_signed_in?
      cat_params = params.require(:cat).permit(:description, :price, :title, :item_picture)
      @cat = Cat.new(cat_params)
    else
      flash[:warning] = "You must login to use your cart"
      redirect_to new_user_session_path
    end
    if @cat.save
      @cat.update(seller_id: current_user.id)
      redirect_to root_path, flash: { success: "Votre image à bien été enregistrer" }
    else
      render 'new'
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    cat_params = params.permit(:description, :price, :title, :item_picture)
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to root_path, notice: "Votre image à bien été editer"
    else
      render 'edit', alert: "Veuillez réessayer"
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    # @cat.destroy
    if @cat.toggle(:is_available).save
      redirect_to root_path, notice: "Votre modification a bien été prise en compte"
    else
      render :edit, warning: "Votre modification n'a pas pu être appliquée"
    end
  end

  private

  def seller_cat
    @seller = Cat.find(params[:id]).user_id
  end
end

app/helpers/cats_helper.rb
# frozen_string_literal: true

module CatsHelper
  def current_cart_cats_quantity(cat_id)
    @id = cat_id
    CartCat.where(cart_id: current_cart).find_by(cat_id: @id)&.quantity if user_signed_in?
  end

  def seller_email(cat)
    cat.seller ? cat.seller.email : "NextKittens"
  end
end

app/views/admin/cats/edit.html.erb
<%= render 'cats/banner' %>

<div class="component-example">
  <div class="row justify-content-center">
    <h2>Editer ma photo</h2><br>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-md-10 col-lg-6">
      <div class="row mb-4">
        <%= form_tag url_for(action: 'update'), method: "patch", multipart: true do %>
        <div class="col">
          <div class="boxed">
            <div class="row align-items-center justify-content-between p-3">
            <div class="col-md-5">
              <p><b>Photo actuelle</b></p>
              <%if @cat.item_picture.attached?%>
                <%=image_tag @cat.item_picture, alt: 'item picture'%>
                <% else %>
                <%end%>
                <%= label_tag 'Image' %>
                <%= file_field_tag :item_picture %>
             </div>
              
              <div class="col-md-5">
                <p><b>Disponibilité :  </b></p> 
                <p><% if @cat.is_available == true %>
                <%= "Disponibile à la vente" %>
                <% else %>
                <%= "Non disponible à la vente" %>
                <% end %></p>
              
                <%= "Inverser la disponibilité : "%>   
                <%if @cat.is_available == true %>
                <%= check_box_tag(:is_available, "false") %>
                <% else %>
                <%= check_box_tag(:is_available, "true") %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>   
      <div class="row">
        <div class="col">
          <h5 class="mb-2 fs-20 font-weight-normal">Informations Generales</h5>
          <div class="form-row">
            <div class="col">
              <div class="form-group">
                <%= label_tag 'Titre' %>
                <%= text_field_tag 'title', @cat.title, class: "form-control", placeholder:""  %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= label_tag 'Prix' %>
                <%= text_field_tag 'price', @cat.price, class: "form-control", placeholder: "" %>
              </div>
            </div>
          </div>    
        </div>
      </div>
      
      <div class="row">
        <div class="col">
          <h5 class="mb-2 fs-20 font-weight-normal"></h5>
          <div class="form-row">
            <div class="col">  
              <div class="form-group">
                <%= label_tag 'Description' %>
                <%= text_field_tag 'description', @cat.description, class: "form-control", placeholder: "" %>
              </div>
            </div>
          </div>
          <br>
          <div class="row justify-content-center">
            <%= submit_tag "Mettre à jour",  class: "btn btn-primary px-5" %>
          </div> 
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/admin/cats/index.html.erb
    <!-- banner -->
    <%= render 'cats/banner' %>
    <!-- /banner -->

    <!-- sidebar -->
     <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                  <span data-feather="home"></span>
                  <%= link_to "Dashboard", admin_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                  <span data-feather="file"></span>
                  <%= link_to "Orders", admin_carts_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <span data-feather="shopping-cart"></span>
                <%= link_to "Products", admin_cats_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <span data-feather="users"></span>
                <%= link_to "Customers", admin_users_path, class: "nav-link" %>
              </li>
             </ul>
           
              <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <a class="d-flex align-items-center text-muted" href="#">
                </a>
              </h6>
              <ul class="nav flex-column mb-2">
                <li class="nav-item"> 
                  <button type="button" class="btn btn-rounded btn-primary"><%= link_to "Nouvelle image" , new_admin_cat_path, class:"nav-link dropdown"%> <i class="icon-plus2"></i></button>
                </li>
              </ul>
             </div>
        </nav>
      
   
    <!-- /sidebar -->

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <!--<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Items Dashboard</h1>
          </div>

          <canvas class="my-4" id="myChart" width="900" height="380"></canvas> -->

          <h2>Cats pictures preview</h2>
          

              <div class="table-responsive">
                <table class="table table-striped table-sm">
                  <thead>
                    <tr>
                      <th width="15%">Titre</th>
                      <th width="15%">Prix</th>
                      <th width="35%">Vendeur</th>
                      <th width="10%">Voir</th>
                      <th width="10%">Editer</th>
                      <th width="15%">En vente</th>

                    </tr>
                  </thead>
                  <tbody>
                  <% @cats.each do |cat|%>
                    <tr>
                      <td><%= cat.title%></td>
                      <td><%= cat.price%></td>
                      <!-- seller_email defined in helper -->
                      <td><%= seller_email(cat) %></td>
                      <td><span title= "Voir" ><%= link_to '<i class="btn btn-sm btn-ico btn-primary "></i>'.html_safe, cat_path(cat)%></span></td>
                      <td><span title= "Editer" ><%= link_to '<i class="btn btn-sm btn-ico btn-instagram"></i>'.html_safe, edit_admin_cat_path(cat)%></span></td>
                      <td><%= cat.is_available%></td>

                    </tr>
                  <%end%>
                  </tbody>
           </table>
          </div>
        </main>
      </div>
    </div>




     <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

<!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: ["Nb of Carts", "Nb of availble cats", "Nb of confimed carts", "Active seller", "Active buyer"],
          datasets: [{
            data: [<%= Cart.count %>, <%=Cat.where(is_available: true).count%>, <%=Cart.where(status: true).count%>, <%=User.count%>, <%= %> ],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>

app/views/admin/cats/new.html.erb
<%= render 'cats/banner' %>

<div class="component-example">
  <div class="row justify-content-center">
    <h2>Ajouter une nouvelle photo de chat</h2><br>
  </div>

<div class="row justify-content-center">
  <div class="col-md-10 col-lg-6">
    <div class="row mb-4">
    <div class="col">
      <div class="boxed">
        <div class="row align-items-center justify-content-between p-3">
          <p><b>Choose your pic</b></p>
            <div class="col-md-5 text-center text-md-left">
              <%= form_tag url_for(action: 'create'), method: "post", multipart: true do %>
              <%= label_tag 'Image' %> <br>
              <%= file_field_tag :item_picture %>
            </div>
          <div class="col-md-4 text-center text-md-right mt-1 mt-md-0">
        </div>
      </div>
    </div>
   </div>
 </div>
<div class="row">
  <div class="col">
    <h5 class="mb-2 fs-20 font-weight-normal">General Information</h5>
      <div class="form-row">
        <div class="col">
          <div class="form-group">
            <%= label_tag 'Title' %>
            <%= text_field_tag 'title', @cat.title, class: "form-control", placeholder: "" %>
          </div>
        </div>
        <div class="col">
          <div class="form-group">
            <%= label_tag 'Price' %>
            <%= text_field_tag 'price', @cat.price, class: "form-control", placeholder: "" %>
          </div>
        </div>
      </div>
    </div>    
  </div>
  <div class="row">
    <div class="col">
      <h5 class="mb-2 fs-20 font-weight-normal"></h5>
        <div class="form-row">
          <div class="col">
            <div class="form-group">
              <%= label_tag 'Description' %>
              <%= text_area_tag :description, "", class: 'form-control', placeholder: "" %>
            </div>
          </div>
        </div>
        <div class="row justify-content-center">
          <%= submit_tag "Créer",  class: "btn btn-primary px-5" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
            