config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # minimal carts and cats routes for dev purposes
  resources :cats
  resources :cart_cats, only: %i[create update destroy]
  resources :carts
  get 'download_cart_zip', to: "carts#download_cart_zip"
  resources :charges
  resources :profiles

  get 'admin', to: 'admin#index_admin'

  namespace :admin do
    resources :cats
    resources :carts
    resources :users
  end

  # root 'cats#index'
  root 'welcome#index'

  # static_pages
  get 'team_project', to: 'static_pages#team_project'
end

app/models/cart.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: carts
#
#  id           :bigint(8)        not null, primary key
#  order_placed :datetime
#  status       :boolean          default(FALSE), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint(8)
#
# Indexes
#
#  index_carts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_cats, -> { includes :cat }, inverse_of: :cart, dependent: :destroy

  validates :user_id, presence: true
  validates :status, inclusion: { in: [true, false] }
  validates :order_placed, presence: true, if: :status

  def cart_user
    User.find(user_id)
  end

  def total_cart_price
    # cart_cats.map(&:total_cat_price).sum
    CartCat.where(cart_id: id).select(:price, :quantity).map { |c| c.price * c.quantity }.sum
  end

  def total_cart_price_in_cents
    total_cart_price * 100
  end

  def count_cats
    CartCat.where(cart_id: id).select(:quantity).map { |q| q[:quantity] }.sum
  end

  def list_cat_names
    CartCat.where(cart_id: id).map { |c| c.cat.title }
  end

  def zipfile
    ZipCartContent.perform(cart: id)
  end
end

app/controllers/admin/carts_controller.rb
# frozen_string_literal: true

module Admin
  class CartsController < AdminController
    def index
      @carts = Cart.all
    end

    def new
      @cart = Cart.new
    end

    def show
      @cart = Cart.find(params[:id])
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def index; end

  def show
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    current_user.set_current_cart
    redirect_to root_path
  end

  def download_cart_zip
    @cart = Cart.find(params[:cart])
    send_data(ZipCartContent.perform(cart: @cart.id), type: 'application/zip', filename: "NextKittensOrder_#{@cart.id}_#{@cart.order_placed.to_formatted_s(:number)[0..-7]}.zip")
    # TODO: CTRL where should we redirect here ?
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/partials/_cart_dropdown.html.erb
<div class="container">
<div id="drop_cart" class="bg-light" aria-hidden="true" style="display: none">
  <div class="card">
    <div class="card-body">
      <h6 class="card-title">Votre panier</h6>
      <% if current_cart.cart_cats.empty? %>
        <div class="d-flex flex-column justify-content-center align-content-center align-items-center m-10">
          <h5 class="text-center">Votre panier est actuellement vide !</h5>
          <%= link_to "Commencer mes achats", root_path, class: "btn btn-primary btn-large" %>
        </div>
      <% else %>
      <ul class="list-unstyled">
          <%= render partial: 'carts/partials/cart_dropdown_list', collection: current_cart.cart_cats %>
      </ul>
      <hr/>
      <div class="d-flex justify-content-between">
          <span class="text-muted">Total :</span>
          <span class="text-right"><%= number_to_currency(current_cart.total_cart_price) %></span>
        </div>
      <%= link_to "Acheter", cart_path(current_cart), class: "btn btn-primary m-2" %>
      <div>
        <small class="text-muted">Vous pourrez modifier votre commande dans le panier.</small>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/carts/partials/_cart_dropdown_list.html.erb
<li class="list-group-item d-flex justify-content-between lh-condensed">
  <div class="flex-shrink-1 w-50">
    <h6 class="font-weight-bold"><%= cart_dropdown_list.cat.title %></h6>
    <small class="text-muted"><%= cart_dropdown_list.quantity %></small>
  </div>
</li>

app/views/carts/partials/_ordered_carts.html.erb
<li class="list-group-item d-flex justify-content-between lh-condensed">
  <div class="flex-shrink-1 w-50">
    <span class="font-weight-bold"><%= cart.list_cat_names.join(", ") %></span>
    <small class="text-muted">(<%= cart.count_cats %> articles)</small>
  </div>
  <span class="flex-shrink-0 w-10"><%= cart.order_placed.strftime("%F")  %></span>
  <div class="flex-shrink-0 w-20">
    <span><%= number_to_currency(cart.total_cart_price) %></span>
    <small><%= link_to "Télécharger", download_cart_zip_path(cart: cart.id) %></small>
  </div>
</li>

app/views/carts/partials/_show_list.html.erb
<li class="list-group-item d-flex justify-content-between lh-condensed">
  <div class="flex-shrink-1 w-50">
    <h6 class="font-weight-bold"><%= show_list.cat.title %></h6>
    <small class="text-muted"><%= show_list.cat.description %></small>
  </div>
  <span class="flex-shrink-0 w-10"><%= number_to_currency(show_list.price) %></span>
  <span class="flex-shrink-0 w-10"><%= show_list.quantity %></span>
  <span class="flex-shrink-0 w-10"><%= number_to_currency(show_list.total_cat_price) %></span>
  <span class="flex-shrink-0 w-10">
    <!-- TODO: modify quantity instead of delete-->
    <%= link_to "supprimer", cart_cat_path(show_list.id), method: :delete, class: 'text-warning' %>
  </span>
</li>