config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # minimal carts and cats routes for dev purposes
  resources :cats
  resources :cart_cats, only: %i[create update destroy]
  resources :carts
  get 'download_cart_zip', to: "carts#download_cart_zip"
  resources :charges
  resources :profiles

  get 'admin', to: 'admin#index_admin'

  namespace :admin do
    resources :cats
    resources :carts
    resources :users
  end

  # root 'cats#index'
  root 'welcome#index'

  # static_pages
  get 'team_project', to: 'static_pages#team_project'
end

app/models/cart.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: carts
#
#  id           :bigint(8)        not null, primary key
#  order_placed :datetime
#  status       :boolean          default(FALSE), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint(8)
#
# Indexes
#
#  index_carts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_cats, -> { includes :cat }, inverse_of: :cart, dependent: :destroy

  validates :user_id, presence: true
  validates :status, inclusion: { in: [true, false] }
  validates :order_placed, presence: true, if: :status

  def cart_user
    User.find(user_id)
  end

  def total_cart_price
    # cart_cats.map(&:total_cat_price).sum
    CartCat.where(cart_id: id).select(:price, :quantity).map { |c| c.price * c.quantity }.sum
  end

  def total_cart_price_in_cents
    total_cart_price * 100
  end

  def count_cats
    CartCat.where(cart_id: id).select(:quantity).map { |q| q[:quantity] }.sum
  end

  def list_cat_names
    CartCat.where(cart_id: id).map { |c| c.cat.title }
  end

  def zipfile
    ZipCartContent.perform(cart: id)
  end
end

app/controllers/admin/carts_controller.rb
# frozen_string_literal: true

module Admin
  class CartsController < AdminController
    def index
      @carts = Cart.all
    end

    def new
      @cart = Cart.new
    end

    def show
      @cart = Cart.find(params[:id])
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def index; end

  def show
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    current_user.set_current_cart
    redirect_to root_path
  end

  def download_cart_zip
    @cart = Cart.find(params[:cart])
    send_data(ZipCartContent.perform(cart: @cart.id), type: 'application/zip', filename: "NextKittensOrder_#{@cart.id}_#{@cart.order_placed.to_formatted_s(:number)[0..-7]}.zip")
    # TODO: CTRL where should we redirect here ?
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/_banner.html.erb
<section class="bg-primary text-white pattern">
  <div class="container pt-10">
    <div class="row mb-2">
      <div class="col-md-8 col-lg-6">
        <h1>Panier <%= @cart.id %></h1>
        <p><%= @cart.user.email %></p>
      </div>
    </div>
  </div>
</section>

app/views/carts/show.html.erb
<section class="bg-primary text-white pattern" data-top-top="transform: translateY(0px);"
         data-top-bottom="transform: translateY(250px);">
  <div class="container pt-10">
    <div class="row mb-2 pb-2">
      <div class="col-md-8 col-lg-6">
        <h1>Votre panier</h1>
        <p><%= @cart.user.email %></p>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="container">
    <!-- TODO: CSS fix spacing -->
    <div class="row">
      <!-- Section table des achats -->
      <div class="col-md-8">
        <h4>Votre panier</h4>
        <ul class="list-group bg-light">
          <li class="list-group-item d-flex justify-content-between lh-condensed bg-white">
            <h6 class="flex-shrink-1 w-50">Nom</h6>
            <span class="flex-shrink-0 w-10">Prix</span>
            <span class="flex-shrink-0 w-10">Quantité</span>
            <span class="flex-shrink-0 w-10">Total</span>
            <span class="flex-shrink-0 w-20"> </span>
          </li>
          <% if @cart.cart_cats.empty? %>
            <div class="d-flex flex-column justify-content-center align-content-center align-items-center m-10">
              <h5>Votre panier est actuellement vide !</h5>
              <%= link_to "Commencer mes achats", root_path, class: "btn btn-primary btn-large" %>
            </div>
          <% else %>
            <%= render partial: 'carts/partials/show_list', collection: @cart.cart_cats %>
          <% end %>
          <li class="list-group-item d-flex justify-content-between lh-condensed bg-white">
            <span class="w-20">
              <%= link_to "Continue Shopping", cats_path, class: "btn btn-outline-primary btn-sm m-1" %>
            </span>
            <span class="w-80"></span>
            <% if !@cart.total_cart_price.zero? %>
            <span class="align-content-end">
              <%= form_tag charges_path do %>
              <article>
                <% if flash[:error].present? %>
                <div id="error_explanation">
                  <p><%= flash[:error] %></p>
                </div>
                <% end %>
                <label style="font-size: 12pt; color: black;">
                  <span>Total : <%= number_to_currency(@cart.total_cart_price) %></span>
                  <%= hidden_field_tag :amount, @cart.total_cart_price %>
                </label>
                <%= hidden_field_tag :cart_id, @cart.id %>
              </article>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>" data-amount="<%= @cart.total_cart_price_in_cents %>"
                      data-email="<%= @cart.user.email %>" data-name="NextKittens"
                      data-description="The best kitten pictures!" data-panel-label="Paiement de {{amount}}"
                      data-image="<%= asset_url('Kitten_logo.png') %>" data-allow-remember-me="false" data-locale="fr"
                      data-currency="EUR">
              </script>
              <% end %>
            </span>
            <% end %>
          </li>
        </ul>
        <span class="w-10"><%= link_to "vider le panier", cart_path(@cart.id), method: :delete, class: "text-danger" %>
        </span>
      </div>
      <!-- Section informations -->
      <div class="col-md-4">
        <h4>Déroulement</h4>
        <div class="accordion-group accordion-group-steps" data-accordion-group>
          <div class="accordion" data-accordion>
            <div class="accordion-control" data-control>
              <h5>Paiement</h5>
            </div>
            <div class="accordion-content" data-content>
              <div class="accordion-content-wrapper">
                <p>Votre paiement est sécurisé par Stripe</p>
              </div>
            </div>
          </div>
          <div class="accordion" data-accordion>
            <div class="accordion-control" data-control>
              <h5>Téléchargement</h5>
            </div>
            <div class="accordion-content" data-content>
              <div class="accordion-content-wrapper">
                <p>Une version digitale de vos achats est immédiatement disponible</p>
              </div>
            </div>
          </div>
          <div class="accordion" data-accordion>
            <div class="accordion-control" data-control>
              <h5>Expédition</h5>
            </div>
            <div class="accordion-content" data-content>
              <div class="accordion-content-wrapper">
                <p>Votre commande sera expédiée</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>